# Generated by Django 5.2.5 on 2025-08-16 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('announcement_type', models.CharField(choices=[('welfare', 'Welfare'), ('educational', 'Educational'), ('other', 'Other'), ('commercial', 'Commercial')], max_length=20)),
                ('ward_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, null=True, upload_to='announcements_files/')),
            ],
        ),
    ]
