# Generated by Django 5.2.5 on 2025-08-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
