# Generated by Django 5.2.5 on 2025-08-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('scheme_type', models.CharField(choices=[('Education', 'Education'), ('Health', 'Health'), ('Agriculture', 'Agriculture'), ('Employment', 'Employment'), ('Housing', 'Housing'), ('Other', 'Other')], max_length=50)),
                ('eligibility', models.TextField(help_text='Who is eligible for this scheme?')),
                ('benefits', models.TextField(help_text='What benefits does this scheme provide?')),
                ('required_documents', models.TextField(help_text='List of documents required')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
